name: pkgraph
version: 2.0.0
description: A tool for studying and visualizing Dart package dependencies using the Neo4j graph database.
author: George Lesica <george@lesica.com>
homepage: https://github.com/glesica/pkgraph

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.5.1
  http: ^0.12.0
  logging: ^0.11.0
  meta: ^1.1.0
  path: ^1.6.2
  pub_semver: ^1.4.2
  json_annotation: ^2.0.0
  yaml: ^2.1.15

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: ^1.0.0
